# See https://symfony.com/doc/current/email/dev_environment.html
#swiftmailer:
#    send all emails to a specific address
#    delivery_addresses: ['me@example.com']
swiftmailer:
    transport: smtp
    host: smtp.gmail.com 
    port: 587
    encryption: tls
    username: 'projectauth0'
    password: 'vcvjjbxyknvbrdzs'